Nye Retningslinjer og Vedtekter om etterfylling
cybernetisk/fordelingsutvalget pull request #106
Opened 2023-11-19 17:41 UTC by injuul

2023-11-19 17:42 UTC, injuul commented
funke herre?

2023-11-19 17:52 UTC, injuul commented
@Phix151 sjekker du at det ser bra ut?

2024-03-13 14:05 UTC, peterhpo requested changes
Som nevnt i kommentarer flere steder, lag heller ny fil med likt filnavn som disse, men med datoen hvor det ble vedtatt

2024-03-13 14:05 UTC, peterhpo commented on pages/2022-04-26-retningslinjer.md
Lag heller en ny fil med samme formatet som filnavnet til denne, men med dato for møtet hvor det ble vedtatt

2024-03-13 14:05 UTC, peterhpo commented on pages/2022-04-26-vedtekter.md
Gjelder samme som den over

2024-10-14 23:23 UTC, closed without merging